"""Reads from and writes to the OAC catalog via MCP, shared by the adapter, the CLI and the scripts."""
import json
import re

from liveinsight.platforms.oac.mcp import OacMcp, payload_of
from liveinsight.engine.spec import DatasetInfo
from liveinsight.messages import UiError

MY_FOLDERS = "Le mie cartelle"
TEST_FOLDER = "Live Insight - test"      # the only folder Live Insight writes to (rule in CLAUDE.md)


def workbook_json(mcp: OacMcp, name: str) -> dict:
    """The definition (_projectdefn) of the workbook with that exact name."""
    items = payload_of(mcp.call("search_catalog", search=name, types=["workbooks"]))["items"]
    item = next((w for w in items if w["name"] == name), None)
    if item is None:
        raise LookupError(f"workbook '{name}' not found in the catalog")
    body = json.loads(mcp.read_resource(item["contentResource"])[0]["text"])
    return body.get("json", body)


def folder_label(path: str) -> str:
    """Name of the folder holding the object; the personal folder (named after the email) becomes 'Le mie cartelle'."""
    parts = [p for p in (path or "").split("/") if p and p != "@Catalog"]
    parent = parts[-2] if len(parts) >= 2 else ""
    return MY_FOLDERS if "@" in parent or parent in ("", "users") else parent


def list_datasets(mcp: OacMcp, search: str = "*", limit: int = 200) -> list[dict]:
    """Datasets the user can see: name, xsaExpr (the identifier, never the name), folder."""
    items = payload_of(mcp.call("search_catalog", search=search or "*", types=["datasets"], limit=limit))["items"]
    return [{"name": i["name"], "xsa": i["xsaExpr"], "folder": folder_label(i.get("path", ""))}
            for i in items if i.get("xsaExpr")]


def describe(mcp: OacMcp, xsa: str) -> DatasetInfo:
    return DatasetInfo.from_describe(xsa, payload_of(mcp.call("describe_data", datamodelName=xsa)))


def save_workbook(mcp: OacMcp, name: str, definition: dict, description="Generated by Live Insight") -> str:
    """Creates the workbook in TEST_FOLDER and returns the name it was saved with.

    Never overwrites: if the name is taken in the folder it uses "Name (2)", "Name (3)"… (the folder also holds the
    "Varianti" template). userApproved=True because the call starts from the user's click on "Save to OAC".
    OAC's answer gives the path (with the email), not the id: it is not returned.
    """
    folders = [f for f in payload_of(mcp.call("search_catalog", search=TEST_FOLDER, types=["folders"]))["items"]
               if f["name"] == TEST_FOLDER]
    if len(folders) != 1:
        if not folders:
            raise UiError(f"folder '{TEST_FOLDER}' not found in the catalog", "errors.testFolderMissing", folder=TEST_FOLDER)
        raise UiError(f"{len(folders)} folders '{TEST_FOLDER}' in the catalog: which one?", "errors.testFolderAmbiguous",
                      folder=TEST_FOLDER, count=len(folders))
    folder = folders[0]
    taken = {w["name"] for w in payload_of(mcp.call("search_catalog", search="*", types=["workbooks"],
                                                    rootFolder=folder["id"]))["items"]}
    final = name
    n = 2
    while final in taken:
        final = f"{name} ({n})"
        n += 1
    saved = payload_of(mcp.call("save_catalog_content", type="workbooks", name=final, parentId=folder["id"],
                                content={"json": definition}, description=description, userApproved=True))
    if saved.get("status") != "ok":
        raise UiError(f"OAC did not save the workbook (status {saved.get('status')!r})",   # no path: it has the email
                      "errors.oacDidNotSave", status=str(saved.get("status")))
    return final


def safe_filename(name: str) -> str:
    return re.sub(r"[^\w\- ]", "_", name).strip() or "workbook"
