"""M2 — A generated workbook that POINTS to a catalog dataset, without embedding it.

1. the templates ("Examples", "Example 2") are read from the catalog via MCP (resources/read);
2. source and table come from the MCP metadata (search_catalog.xsaExpr, describe_data);
3. the specification is TEST6's, whose numbers are already verified in OAC;
4. the workbook is saved in the "Live Insight - test" folder with save_catalog_content (only there: the project
   writes to one test folder, never elsewhere);
5. export_workbook renders a PNG of it, to see what OAC draws.

Usage:  uv run python spikes/m2_catalog_workbook.py [folder-for-the-png]
"""
import base64
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from liveinsight.platforms.oac.li_dva import Workbook                                                     # noqa: E402
from liveinsight.platforms.oac.auth import OacToken                                       # noqa: E402
from liveinsight.platforms.oac.mcp import OacMcp, payload_of                              # noqa: E402

FOLDER = "Live Insight - test"
NAME = "M2 - Dataset from the catalog"


def workbook_json(mcp, name):
    item = next(w for w in payload_of(mcp.call("search_catalog", search=name, types=["workbooks"]))["items"]
                if w["name"] == name)
    body = json.loads(mcp.read_resource(item["contentResource"])[0]["text"])
    return body.get("json", body)


def build_test6(wb):
    """The TEST6 specification, whose numbers are verified in OAC."""
    wb.reset()
    wb.column("CustomerSegment", "Customer Segment")
    wb.column("OrderPriority", "Order Priority")
    wb.column("Sales", "Sales")
    wb.date_column("OrderQuarter", "Order Date", "quarter")
    wb.date_column("OrderYear", "Order Date", "year")
    wb.calculation("AvgOrderValue", "Average order value", "{Sales} / (COUNT(DISTINCT {Order ID}))",
                   "Created by Live Insight: sales divided by the number of distinct orders.")
    c = wb.canvas("Sales")
    wb.visual(c, "bar", "Average order value by segment",
              {"measures": ["AvgOrderValue"], "detail": ["CustomerSegment"]}, (0, 0, 560, 380))
    wb.visual(c, "line", "Sales by quarter",
              {"measures": ["Sales"], "detail": ["OrderQuarter"]}, (570, 0, 810, 380))
    wb.visual(c, "pivot", "Sales by priority and year",
              {"row": ["OrderPriority"], "col": ["OrderYear"], "measures": ["Sales"]}, (0, 390, 1380, 300))


def main(out_dir):
    load_dotenv(ROOT / ".env")
    token = OacToken.from_file(os.environ["OAC_URL"], ROOT / os.environ["OAC_TOKENS"])
    with OacMcp(os.environ["OAC_URL"], token, timeout=600) as mcp:
        ds = next(i for i in payload_of(mcp.call("search_catalog", search="Retail Orders", types=["datasets"]))["items"]
                  if i.get("xsaExpr"))
        table = payload_of(mcp.call("describe_data", datamodelName=ds["xsaExpr"], tablesOnly=True))["tables"][0]["tableName"]

        wb = Workbook(workbook_json(mcp, "Examples"), extra_templates=[workbook_json(mcp, "Example 2")])
        wb.set_source(ds["xsaExpr"], table)
        build_test6(wb)

        folder = next(f for f in payload_of(mcp.call("search_catalog", search=FOLDER, types=["folders"]))["items"]
                      if f["name"] == FOLDER)
        def ours():
            return [w for w in payload_of(mcp.call("search_catalog", search=NAME, types=["workbooks"],
                                                   rootFolder=folder["id"]))["items"] if w["name"] == NAME]
        existing = ours()
        args = {"type": "workbooks", "content": {"json": wb.definition()}, "userApproved": True,
                "description": "Generated by Live Insight (M2): points to the catalog dataset, no embedded data."}
        if existing:                                 # replaces only a workbook we created, in this folder
            args["id"] = existing[0]["contentResource"].rsplit("/", 1)[1]
        else:
            args.update(name=NAME, parentId=folder["id"])
        saved = payload_of(mcp.call("save_catalog_content", **args))
        print(f"saved ({saved.get('mode')}): status={saved.get('status')} success={saved.get('item', {}).get('success')}")
        if saved.get("status") != "ok":
            print(json.dumps(saved)[:2000])
            return 1
        wid = ours()[0]["contentResource"].rsplit("/", 1)[1]       # the answer gives the path, not the id

        # read back: did OAC save exactly our definition?
        stored = json.loads(mcp.read_resource(f"content://catalog/workbooks/{wid}")[0]["text"])
        stored = stored.get("json", stored)
        same = stored == wb.definition()
        print(f"definition read back from the catalog identical to the generated one: {same}")
        if not same:
            diff = [k for k in set(stored) | set(wb.definition()) if stored.get(k) != wb.definition().get(k)]
            print("  different sections:", diff)

        result = mcp.call("export_workbook", workbookId=wid, format="png", screenWidth=1600, screenHeight=900)
        images = [c for c in result.get("content", []) if c.get("type") == "image"]
        out = Path(out_dir)
        out.mkdir(parents=True, exist_ok=True)
        for i, img in enumerate(images):
            p = out / f"m2_canvas{i + 1}.png"
            p.write_bytes(base64.b64decode(img["data"]))
            print("PNG:", p)
        if not images:
            print("no image:", json.dumps(result)[:1500])
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else ROOT / "out"))
