"""Development tools: save a generated workbook in the OAC folder "Live Insight - test" and export its PNGs. Only
that folder: the project never writes anywhere else in the catalog."""
import base64
import json
from pathlib import Path

from liveinsight.platforms.oac.mcp import payload_of

FOLDER = "Live Insight - test"


def catalog_json(mcp, name):
    """The definition of a catalog workbook (by exact name)."""
    item = next(w for w in payload_of(mcp.call("search_catalog", search=name, types=["workbooks"]))["items"]
                if w["name"] == name)
    body = json.loads(mcp.read_resource(item["contentResource"])[0]["text"])
    return body.get("json", body)


def dataset_by_xsa(mcp, xsa):
    """describe_data of the dataset identified by xsaExpr (never by name: copies with the same name can exist)."""
    return payload_of(mcp.call("describe_data", datamodelName=xsa))


def save_in_test_folder(mcp, name, definition, description="Generated by Live Insight"):
    """Creates or replaces the workbook `name` in the test folder; returns its id."""
    folder = next(f for f in payload_of(mcp.call("search_catalog", search=FOLDER, types=["folders"]))["items"]
                  if f["name"] == FOLDER)

    def ours():
        return [w for w in payload_of(mcp.call("search_catalog", search=name, types=["workbooks"],
                                               rootFolder=folder["id"]))["items"] if w["name"] == name]
    existing = ours()
    args = {"type": "workbooks", "content": {"json": definition}, "userApproved": True, "description": description}
    if existing:
        args["id"] = existing[0]["contentResource"].rsplit("/", 1)[1]
    else:
        args.update(name=name, parentId=folder["id"])
    saved = payload_of(mcp.call("save_catalog_content", **args))
    if saved.get("status") != "ok":
        raise RuntimeError(json.dumps(saved)[:2000])
    return ours()[0]["contentResource"].rsplit("/", 1)[1]


def export_png(mcp, workbook_id, out_dir, prefix, width=1600, height=900):
    result = mcp.call("export_workbook", workbookId=workbook_id, format="png", screenWidth=width, screenHeight=height)
    paths = []
    for i, img in enumerate(c for c in result.get("content", []) if c.get("type") == "image"):
        p = Path(out_dir) / f"{prefix}_{i + 1}.png"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(base64.b64decode(img["data"]))
        paths.append(p)
    return paths
